datasift:
  username: rich_caudle
  apikey: bc583ac6e70761eb16f4f67e128ea824
  query: twitter.text contains "mcfc"
topics:
  -
    name: Users
    category: twitter-mention
  -
    name: Hashtags
    category: twitter-hashtag