datasift:
  username: 
  apikey: 
  query: interaction.content contains "mcfc" AND interaction.type == "twitter"
twitter:
  apikey: 
  apisecret: 
  accesstoken: 
  accesstokensecret: 
topics:
  -
    name: Users
    category: twitter-mention
  -
    name: Hashtags
    category: twitter-hashtag